export type AnswerInlineFragment = {
  type: "text" | "strong" | "em";
  text: string;
};

export type AnswerContentBlock =
  | { type: "heading" | "paragraph" | "strong"; text: string }
  | { type: "inlineParagraph"; fragments: AnswerInlineFragment[] }
  | { type: "accessLevel"; icon: string; label: string; definition: string }
  | { type: "example"; lines: string[] };

export type Answer = {
  slug: string;
  path: string;
  title: string;
  description: string;
  datePublished: string;
  content: AnswerContentBlock[];
};

export const answers: Answer[] = [
  {
    slug: "make-friends-through-mutual-friends",
    path: "/answers/make-friends-through-mutual-friends",
    title: "How do you make friends through mutual friends?",
    description: "Making friends through mutual friends is about seeing the people you click with again, making another plan and letting social circles naturally overlap.",
    datePublished: "2026-09-01",
    content: [
      { type: "inlineParagraph", fragments: [
        { type: "text", text: "Making friends through mutual friends is less about meeting as many people as possible and more about " },
        { type: "strong", text: "seeing the people you click with again" },
        { type: "text", text: "." },
      ] },
      { type: "inlineParagraph", fragments: [
        { type: "text", text: "Spend time in plans where you'll meet each other's friends. If you get on with someone, include them the next time you're doing something. That's how someone goes from " },
        { type: "em", text: "your friend's friend" },
        { type: "text", text: " to someone you have a friendship with yourself." },
      ] },
      { type: "inlineParagraph", fragments: [
        { type: "text", text: "Loopt is designed to make that easier. Friends can add friends to plans, so different social circles can naturally overlap. And if you meet someone through a plan, " },
        { type: "strong", text: "you can add them to a future plan yourself, even if you never exchanged numbers." },
      ] },
      { type: "strong", text: "A mutual friend can make the introduction. Another plan can turn that introduction into a friendship." },
      { type: "heading", text: "Let friends bring friends" },
      { type: "paragraph", text: "You don't need to organise a formal introduction to everyone your friends know." },
      { type: "paragraph", text: "Sometimes it's as simple as getting a few people together and letting them bring people they think will enjoy it." },
      { type: "inlineParagraph", fragments: [
        { type: "text", text: "On Loopt, " },
        { type: "strong", text: "Open access" },
        { type: "text", text: " means people can add people they know, and those people can add people too. So a plan can start with a few existing friends and grow naturally through them." },
      ] },
      { type: "paragraph", text: "That could mean your friend brings their housemate to the pub. Someone adds a friend from work to Sunday lunch. A few different friendship groups end up at the same birthday drinks." },
      { type: "paragraph", text: "You spend time with people you already know while naturally meeting some people you don't." },
      { type: "heading", text: "See the people you click with again" },
      { type: "paragraph", text: "Meeting someone once doesn't automatically make you friends." },
      { type: "paragraph", text: "The important bit is creating another opportunity to spend time together." },
      { type: "paragraph", text: "That doesn't have to mean immediately asking someone you've just met to hang out one-to-one. Include them in drinks you're already organising. Add them to something a few of you are doing. Make another plan with some of the same people." },
      { type: "inlineParagraph", fragments: [
        { type: "text", text: "On Loopt, plans create shared social context between people. If you met someone through a plan, " },
        { type: "strong", text: "you can add them to another plan later." },
      ] },
      { type: "paragraph", text: "So you don't need to have exchanged numbers, or rely on the original mutual friend to bring everyone together again." },
      { type: "heading", text: "Let your new connections introduce you to theirs" },
      { type: "paragraph", text: "This is where friendship groups can start growing in a really natural way." },
      { type: "paragraph", text: "Your friend brings someone you haven't met." },
      { type: "paragraph", text: "You get on and start including them in things." },
      { type: "paragraph", text: "They bring someone they know to another plan." },
      { type: "paragraph", text: "Now you meet them too." },
      { type: "paragraph", text: "It doesn't need to be a deliberate exercise in “expanding your network”. You're just spending time with people, meeting more of each other's friends and seeing the people you like again." },
      { type: "paragraph", text: "Over time, separate friendship groups can start to overlap." },
      { type: "heading", text: "You don't need to meet loads of new people" },
      { type: "paragraph", text: "Making friends through mutual friends isn't about turning every plan into a networking event." },
      { type: "paragraph", text: "Spend time with your existing friends. Be open to the people they bring. Bring some of your own friends when it makes sense." },
      { type: "paragraph", text: "Then notice who you naturally want to see again." },
      { type: "paragraph", text: "One new person you really get on with is more meaningful than meeting a room full of people once and never seeing them again." },
      { type: "heading", text: "Let friendships grow through plans" },
      { type: "paragraph", text: "The nice thing about mutual friends is that new friendships don't have to start completely from scratch." },
      { type: "paragraph", text: "Someone you trust brings someone they know. You spend time together. If you get on, you see each other again." },
      { type: "paragraph", text: "Then that new person might introduce you to more of their friends too." },
      { type: "inlineParagraph", fragments: [
        { type: "text", text: "That's one of the ideas behind Loopt: " },
        { type: "strong", text: "plans can grow through people, and so can your social circle." },
      ] },
      { type: "paragraph", text: "You don't need to deliberately build a network. Keep making plans, open some of them up when it feels right, and make it easy to spend time again with the people you meet along the way." },
    ],
  },
  {
    slug: "tell-friends-they-can-bring-other-people",
    path: "/answers/tell-friends-they-can-bring-other-people",
    title: "How do you tell friends they can bring other people to a plan?",
    description: "Tell friends they can bring other people by making the plan's access clear, from Them only and Plus one to Open access for friends of friends.",
    datePublished: "2026-09-01",
    content: [
      { type: "paragraph", text: "The easiest way is to make it clear from the start how open the plan is." },
      { type: "paragraph", text: "Sometimes you only want the people you've asked. Sometimes you'd be happy for everyone to bring one other person. And sometimes the whole point is to open the plan up and let friends bring friends." },
      { type: "paragraph", text: "Making that clear means nobody has to awkwardly ask, “Is it okay if I bring someone?” or guess whether an extra person would be welcome." },
      { type: "heading", text: "Decide how open you actually want the plan to be" },
      { type: "paragraph", text: "Not every plan needs the same rule." },
      { type: "paragraph", text: "If you've booked dinner for six people, you might need to know exactly who's coming." },
      { type: "paragraph", text: "If you're having people over, you might be happy for a friend to bring their partner or someone they know." },
      { type: "paragraph", text: "And if you're getting a group together at the pub, you might genuinely think: the more the merrier." },
      { type: "paragraph", text: "Before telling people they can bring others, work out which kind of plan this is." },
      { type: "paragraph", text: "It doesn't have to be either completely closed or completely open." },
      { type: "heading", text: "Loopt lets you make that permission part of the plan" },
      { type: "paragraph", text: "On Loopt, you can decide how much access people have to add others." },
      { type: "paragraph", text: "There are three levels:" },
      { type: "accessLevel", icon: "/invite_only_symbol.svg", label: "Them only", definition: "means they're included in the plan, but they can't add anyone else." },
      { type: "accessLevel", icon: "/plus_one_symbol.svg", label: "Plus one", definition: "means they can add one other person." },
      { type: "accessLevel", icon: "/bring_friends_symbol.svg", label: "Open access", definition: "means they can add people they know, and those people can add people too. That means the plan can keep growing naturally through the people already involved." },
      { type: "paragraph", text: "You can set a default for the plan and then tailor someone's access individually if you need to." },
      { type: "paragraph", text: "Other people don't need to see the access you've chosen for everyone else. They simply get the ability that's relevant to them. So if someone has them-only access, for example, they won't see an option to add another person." },
      { type: "paragraph", text: "That removes some of the awkwardness from both sides. You don't have to tell someone “please don't bring anyone else”, and they don't have to wonder whether they're supposed to ask." },
      { type: "paragraph", text: "If it's particularly important, you can still say in the plan that people should bring friends, or that you're keeping this one small." },
      { type: "heading", text: "Opening a plan can be a really nice way to meet more people" },
      { type: "paragraph", text: "There's also a reason you might deliberately want to make a plan more open." },
      { type: "paragraph", text: "Friendship groups can easily stay separate." },
      { type: "paragraph", text: "You have your friends from work. Someone else has their housemates. Another friend has people they know from uni. You might hear about these people all the time without actually spending much time with them." },
      { type: "paragraph", text: "An open plan gives those circles somewhere to overlap." },
      { type: "paragraph", text: "You add a few people. They add people they think would enjoy it. Those people can bring others too." },
      { type: "paragraph", text: "Suddenly you're not only spending time with the friends you already know. You're meeting more of each other's people through people you already trust." },
      { type: "paragraph", text: "And sometimes you really click with one of them." },
      { type: "paragraph", text: "That's how a plan for a few drinks can gradually lead to a bigger social circle, without anyone having to organise a formal way for everyone to meet." },
      { type: "heading", text: "Open access doesn't mean unlimited" },
      { type: "paragraph", text: "Of course, “bring people” can become a problem if you only have space for twelve." },
      { type: "paragraph", text: "Opening a plan doesn't mean giving up control over its size." },
      { type: "paragraph", text: "If you know the limit from the beginning, you can put a cap on the plan. People can add others while there's space, but the plan can't keep growing beyond the number you've set." },
      { type: "paragraph", text: "Or you can start with an open plan and see how it develops. Once you've got enough people, you can stop sharing it so people can't keep adding others." },
      { type: "paragraph", text: "So you can get the nice part of an open plan, where friends bring friends and different circles start mixing, without having to leave the plan open indefinitely." },
      { type: "heading", text: "You can give different people different access" },
      { type: "paragraph", text: "Sometimes one rule for everyone doesn't quite work." },
      { type: "paragraph", text: "Maybe you'd love one friend to bring their housemates, while another person has already asked whether they can bring their partner and that's all the extra space you have." },
      { type: "paragraph", text: "Loopt lets you tailor people's add access when you need to, rather than applying exactly the same rule to everybody." },
      { type: "paragraph", text: "That means you can be quite open about who brings people without losing the ability to shape the plan when it matters." },
      { type: "paragraph", text: "Most casual plans probably won't need much thought at all. Set the access that makes sense and get on with making the plan." },
      { type: "paragraph", text: "But the flexibility is there when you need it." },
      { type: "heading", text: "Make it easy for your social circles to overlap" },
      { type: "paragraph", text: "If you're happy for people to bring friends, the most useful thing you can do is make that clear." },
      { type: "paragraph", text: "It saves everyone from trying to work out an unwritten social rule." },
      { type: "paragraph", text: "And being a little more open can have benefits beyond making one plan bigger." },
      { type: "paragraph", text: "Your friends get to meet more of your friends. You meet more of theirs. People who get on can see each other again. Over time, separate friendship groups can start to overlap." },
      { type: "paragraph", text: "You don't have to open every plan." },
      { type: "paragraph", text: "But when it feels right, letting people bring people can create more opportunities for everyone to spend time together." },
    ],
  },
  {
    slug: "dont-make-friends-during-freshers-week",
    path: "/answers/dont-make-friends-during-freshers-week",
    title: "What if I don't make friends during Freshers' Week?",
    description: "Not making friends during Freshers' Week doesn't mean you've missed your chance. Focus on who you'd like to see again, then make another plan.",
    datePublished: "2026-08-31",
    content: [
      { type: "paragraph", text: "If you don't make friends during Freshers' Week, you haven't missed your chance." },
      { type: "paragraph", text: "Freshers' Week is good for meeting lots of people, but meeting people and actually becoming friends with them are different things. Your course, accommodation, societies, sports, jobs and everyday university life will keep putting new people in front of you long after the first week is over." },
      { type: "paragraph", text: "Instead of worrying about whether you've found your friendship group yet, focus on something smaller:" },
      { type: "strong", text: "Who would you like to see again?" },
      { type: "paragraph", text: "Then make that happen." },
      { type: "heading", text: "Freshers' Week isn't a deadline for making friends" },
      { type: "paragraph", text: "University can create the impression that everyone forms a friendship group immediately." },
      { type: "paragraph", text: "You've been there five days and suddenly the people in the flat next door appear inseparable." },
      { type: "paragraph", text: "That doesn't mean those groups are fixed." },
      { type: "paragraph", text: "People keep meeting coursemates once teaching starts. Societies begin holding regular activities. You meet friends of flatmates, people from other halls and people you happened to sit beside in a seminar." },
      { type: "paragraph", text: "Your social life at university is still forming." },
      { type: "heading", text: "Don't just try to meet more people" },
      { type: "paragraph", text: "If Freshers' Week didn't go brilliantly, the instinct can be to meet as many new people as possible." },
      { type: "paragraph", text: "Sometimes the better next step is to go back to the people you've already met." },
      { type: "paragraph", text: "Think about the person you chatted to before a lecture. The flatmate you had a good conversation with in the kitchen. Someone you met at a society. The person you spoke to for twenty minutes at a Freshers' event and haven't seen since." },
      { type: "paragraph", text: "You don't need to know whether they're going to become a close friend." },
      { type: "paragraph", text: "Just create another opportunity to spend time together." },
      { type: "paragraph", text: "Ask if they want to grab coffee after class. Suggest getting lunch before a lecture. See if they fancy going to the next society event together." },
      { type: "paragraph", text: "Small plans are much easier than trying to manufacture an instant friendship group." },
      { type: "heading", text: "Seeing someone again matters more than having a perfect first meeting" },
      { type: "paragraph", text: "A lot of Freshers' Week is introductions." },
      { type: "paragraph", text: "What's your name? Where are you from? What are you studying? Which halls are you in?" },
      { type: "paragraph", text: "You can have that conversation twenty times without becoming close to anyone." },
      { type: "paragraph", text: "Friendships have more chance to develop when you actually keep spending time together." },
      { type: "paragraph", text: "That's why your course and societies can be useful beyond simply helping you meet people. They give you repeated opportunities to see some of the same faces." },
      { type: "paragraph", text: "Then you can take the next step yourself and make a plan outside whatever originally brought you together." },
      { type: "heading", text: "A plan doesn't need to start with a friendship group" },
      { type: "paragraph", text: "This is something Loopt is particularly useful for." },
      { type: "paragraph", text: "Maybe you've met one person on your course and quite like them. You don't need to wait until you've somehow assembled six friends before doing anything." },
      { type: "paragraph", text: "Put up a plan for coffee, a pub trip, a walk, lunch or whatever you're already thinking of doing and add them." },
      { type: "paragraph", text: "You can include other people you've met too. And where you've opened the plan up to it, people can add people they know." },
      { type: "paragraph", text: "So a plan that starts with two people can become three or four. Someone brings their flatmate. Someone else adds a person from their course." },
      { type: "paragraph", text: "You don't need to know everyone at the beginning for the group to start taking shape." },
      { type: "heading", text: "Don't assume everyone else has already found their people" },
      { type: "paragraph", text: "Once you're feeling behind socially, it's very easy to interpret everyone else as settled." },
      { type: "paragraph", text: "But the person you met in your seminar might also be wondering who to have lunch with." },
      { type: "paragraph", text: "Someone going to a society alone might be hoping they'll recognise a familiar face." },
      { type: "paragraph", text: "Making a small plan isn't a declaration that you want to be best friends. You're just giving someone another opportunity to spend time together." },
      { type: "paragraph", text: "And if one person isn't interested or doesn't make it, try someone else." },
      { type: "paragraph", text: "You're looking for the people where spending time together starts to feel easy." },
      { type: "heading", text: "Give it longer than a week" },
      { type: "paragraph", text: "Freshers' Week can help you meet people. It doesn't decide who your university friends will be." },
      { type: "paragraph", text: "Keep going to the places where you naturally see the same people. Talk to your coursemates. Actually turn up to the societies you signed up for. Spend some time in the shared spaces where you live." },
      { type: "paragraph", text: "But don't stop at meeting them." },
      { type: "paragraph", text: "If you like someone, make another plan." },
      { type: "paragraph", text: "Then another." },
      { type: "paragraph", text: "Your university friendship group doesn't have to appear fully formed during Freshers' Week. It can grow one plan and one person at a time." },
    ],
  },
  {
    slug: "make-recurring-plans-with-friends",
    path: "/answers/make-recurring-plans-with-friends",
    title: "How do you make recurring plans with friends?",
    description: "Recurring plans are easier when you reduce repeated organising, whether that means a standing plan or making it simple to bring the same group together again.",
    datePublished: "2026-08-31",
    content: [
      { type: "paragraph", text: "The easiest way to make recurring plans with friends is to remove as much of the repeated organising as possible." },
      { type: "paragraph", text: "For some groups, that means having a standing plan: dinner on the first Thursday of every month, a Sunday morning walk or drinks every other Friday." },
      { type: "paragraph", text: "But recurring plans don't have to mean doing the exact same thing at the exact same time every week." },
      { type: "paragraph", text: "Sometimes the useful thing to repeat is simply the group of people." },
      { type: "heading", text: "A standing plan works when everyone's routine allows it" },
      { type: "paragraph", text: "If you have friends you want to see regularly, choosing a predictable time can save a lot of effort." },
      { type: "paragraph", text: "Instead of starting another conversation every few weeks about when everyone is free, you already know that the first Sunday of the month is brunch or Wednesday evening is five-a-side." },
      { type: "paragraph", text: "It works particularly well when people's schedules are relatively predictable and everyone wants to make the activity a regular part of their routine." },
      { type: "paragraph", text: "But plenty of friendships don't work like that." },
      { type: "paragraph", text: "People travel. Work changes. Someone can't do Thursdays anymore. Or perhaps you don't actually want to do the same thing every month." },
      { type: "paragraph", text: "You can still make it easier to keep getting together." },
      { type: "heading", text: "Repeat the group, not necessarily the plan" },
      { type: "paragraph", text: "Sometimes you have a really good night with a group of people and immediately think: we should do this again." },
      { type: "paragraph", text: "Maybe you knew five of them already. Your friend brought someone from work. Someone else brought two friends from their flat. You got on brilliantly with people you hadn't met before." },
      { type: "paragraph", text: "The next plan doesn't need to be the same activity." },
      { type: "paragraph", text: "Dinner could become drinks. Drinks could become a Sunday roast. Someone else might suggest a gig." },
      { type: "paragraph", text: "What's worth keeping is the group that had a good time together." },
      { type: "heading", text: "On Loopt, a previous plan can help create the next one" },
      { type: "paragraph", text: "Loopt makes it easier to bring people you've spent time with through previous plans into future ones." },
      { type: "paragraph", text: "That matters when a group has grown through friends of friends." },
      { type: "paragraph", text: "You might really get on with someone your friend added to the last plan, without ever exchanging numbers with them. If their connection and privacy settings allow it, you can still add them to another plan later." },
      { type: "paragraph", text: "So you don't necessarily need to ask your friend for their number, rebuild the original group chat or rely on the same person to organise everyone again." },
      { type: "paragraph", text: "Someone can simply make the next plan and bring that group together again." },
      { type: "heading", text: "Let different people start the next plan" },
      { type: "paragraph", text: "Recurring social plans become harder to maintain when one person is responsible for making every single one happen." },
      { type: "paragraph", text: "If nobody does anything until that person sends another message, eventually there may just be no next plan." },
      { type: "paragraph", text: "The next plan doesn't have to come from the person who made the last one." },
      { type: "paragraph", text: "If someone else in the group has an idea, they can put up the next plan and bring people together again." },
      { type: "paragraph", text: "That can make a social circle feel less dependent on one person constantly doing the organising." },
      { type: "heading", text: "You don't need everyone every time" },
      { type: "paragraph", text: "Keeping a group going also doesn't mean recreating exactly the same group for every plan." },
      { type: "paragraph", text: "Six people might make dinner. Four of them might go for drinks the next week. Someone who missed both might make the next plan." },
      { type: "paragraph", text: "What matters is creating enough opportunities for people to keep spending time together." },
      { type: "paragraph", text: "If you require the exact same group to be available every time, recurring plans can quickly become another scheduling problem." },
      { type: "heading", text: "Make the next plan easy to make" },
      { type: "paragraph", text: "Regularly seeing friends doesn't always require a perfectly maintained recurring event." },
      { type: "paragraph", text: "A standing plan can be brilliant when it suits the group. But sometimes friendships are messier and more spontaneous than that." },
      { type: "paragraph", text: "If you've found a group of people who enjoy spending time together, make it easy for someone to start the next plan, bring those people together again and let whoever's free come along." },
      { type: "paragraph", text: "The activity can change. The person making the plan can change. Not everyone has to make every one." },
      { type: "paragraph", text: "The important bit is that there keeps being a next time." },
    ],
  },
  {
    slug: "get-friends-to-commit-to-plans",
    path: "/answers/get-friends-to-commit-to-plans",
    title: "How do you get friends to commit to plans?",
    description: "Getting friends to commit is easier when the plan is concrete, the level of commitment matches the plan and people can give a clear answer.",
    datePublished: "2026-08-31",
    content: [
      { type: "paragraph", text: "You can't force friends to commit to plans, but you can make it much easier for them to give you a clear answer." },
      { type: "paragraph", text: "Start with a specific plan rather than a vague suggestion. Give people something concrete to respond to, make it easy to say yes or no, and don't keep the whole plan waiting indefinitely for everyone to decide." },
      { type: "paragraph", text: "For casual plans, you might not even need a firm commitment from everyone. But when numbers matter, ask for one." },
      { type: "heading", text: "Make the plan concrete first" },
      { type: "paragraph", text: "It's difficult to commit to something that doesn't really exist yet." },
      { type: "paragraph", text: "“Anyone fancy doing something next weekend?” still leaves everyone with several decisions to make. What are you doing? Which day? Where? Who else is going?" },
      { type: "paragraph", text: "Compare that with:" },
      { type: "strong", text: "Dinner at 7pm on Friday at the Italian place on Green Lanes." },
      { type: "paragraph", text: "People can actually decide whether that works for them." },
      { type: "paragraph", text: "The details don't necessarily have to be final, but starting with a real plan gives everyone something to respond to rather than another conversation to continue." },
      { type: "heading", text: "Decide how much commitment you actually need" },
      { type: "paragraph", text: "Not every plan needs a firm yes from every person." },
      { type: "paragraph", text: "If you're going to the pub on Thursday and you'd be happy to see whoever's around, you probably don't need to chase six friends for an answer." },
      { type: "paragraph", text: "Make the plan, let people know what you're doing and go with whoever can make it." },
      { type: "paragraph", text: "It's different if you've booked a table for eight, bought tickets or need to know numbers by a certain time. Then a vague “sounds good” isn't particularly useful." },
      { type: "paragraph", text: "The amount of commitment you ask for should match the plan." },
      { type: "heading", text: "Being in a Loopt plan can keep casual plans low-pressure" },
      { type: "paragraph", text: "For everyday plans on Loopt, you can add the people you'd like to include and they can stay in the plan or leave if they can't make it." },
      { type: "paragraph", text: "That works well when the plan doesn't need a firm headcount. You're essentially signposting what you're doing and giving people the opportunity to come." },
      { type: "paragraph", text: "People can also react to the plan, which can give you a sense that they've seen it and are engaged with it." },
      { type: "paragraph", text: "But someone being in the plan isn't necessarily the same as them explicitly confirming they'll be there." },
      { type: "paragraph", text: "Sometimes that's fine. Sometimes you need a clearer answer." },
      { type: "heading", text: "If you need a firm answer, ask who's in" },
      { type: "paragraph", text: "Loopt Premium's check who's in feature is designed for plans where you need more certainty." },
      { type: "paragraph", text: "People can say I'm in, maybe or can't go, and they can add a note if there's something you need to know." },
      { type: "paragraph", text: "If you need to firm things up closer to the plan, you can send a nudge. Loopt automatically selects people who are still pending or maybe, but you can choose exactly who gets it. So if someone said they're in but added a note like “need to double check, but 90% sure”, you can nudge them too." },
      { type: "paragraph", text: "That means you don't have to work out who's actually coming by interpreting messages like “sounds good”, “should be able to” and “I'll let you know”." },
      { type: "paragraph", text: "It also keeps those responses relatively private. Other people in the plan don't see everyone's yes, maybe or pending status. They mainly see who's in the plan, while the person who made it gets the information they need to understand where people stand." },
      { type: "paragraph", text: "So asking for commitment doesn't have to turn the plan into a public roll call." },
      { type: "heading", text: "Don't keep chasing people forever" },
      { type: "paragraph", text: "If you've made the plan clear and given people a reasonable chance to respond, at some point the plan should be allowed to happen." },
      { type: "paragraph", text: "Five people being in shouldn't necessarily become five people waiting for another three to decide." },
      { type: "paragraph", text: "For something casual, you can simply go ahead with whoever can make it. If you need numbers for a booking, give people a genuine deadline and make the booking based on the answers you have." },
      { type: "paragraph", text: "And if one friend repeatedly commits and then cancels at the last minute, that's a different problem. No planning tool can make somebody reliable." },
      { type: "paragraph", text: "What a better planning process can do is remove some of the ambiguity around who has actually committed in the first place." },
      { type: "heading", text: "Make saying yes easier than saying maybe forever" },
      { type: "paragraph", text: "Getting people to commit isn't really about persuading everyone to come." },
      { type: "paragraph", text: "It's about making the plan concrete enough that people can make a decision, asking for the right level of commitment for that particular plan, and then letting it happen with the people who are actually in." },
      { type: "paragraph", text: "For casual plans, that can stay very low-pressure." },
      { type: "paragraph", text: "And when you genuinely need a yes, no or maybe, make that question explicit rather than trying to piece the answer together from a group chat." },
    ],
  },
  {
    slug: "make-plans-with-friends-when-everyone-is-busy",
    path: "/answers/make-plans-with-friends-when-everyone-is-busy",
    title: "How do you make plans with friends when everyone is busy?",
    description: "When everyone is busy, making the plan first and seeing who can come can be easier than waiting for every friend's calendar to line up.",
    datePublished: "2026-08-31",
    content: [
      { type: "paragraph", text: "When everyone is busy, you don't always need to find a time that works for everyone. Sometimes it's easier to make the plan first and see who can make it." },
      { type: "paragraph", text: "If it's important that the whole group is there, comparing calendars or using a scheduling poll makes sense. But plenty of everyday plans don't need everyone." },
      { type: "paragraph", text: "You're going for a drink after work anyway. You and a friend are getting lunch on Saturday. You're going for a walk on Sunday morning." },
      { type: "paragraph", text: "Put the plan out there and let the people you'd like to see decide if they're free." },
      { type: "paragraph", text: "It turns making plans from a scheduling exercise into something much more casual:" },
      { type: "strong", text: "this is what I'm doing, come if you can." },
      { type: "heading", text: "Decide whether you actually need everyone there" },
      { type: "paragraph", text: "Some plans only work if particular people can make them." },
      { type: "paragraph", text: "If you're organising a birthday dinner for six close friends, finding a date that works for everyone might be worth the effort." },
      { type: "paragraph", text: "But if the aim is simply to spend more time with your friends, requiring everyone to be free at once can make things unnecessarily difficult." },
      { type: "paragraph", text: "The bigger and busier the group gets, the less likely everyone's calendars are to line up." },
      { type: "paragraph", text: "So ask yourself: does everyone need to be there, or would you still have a good time with whoever can make it?" },
      { type: "paragraph", text: "If it's the latter, you can stop solving everyone's calendars before making the plan." },
      { type: "heading", text: "Make the plan first" },
      { type: "paragraph", text: "Say you and one friend are going to the pub on Thursday." },
      { type: "paragraph", text: "Instead of asking eight people when they're next free, make Thursday's plan and add the people you'd be happy to see there." },
      { type: "paragraph", text: "Some might come. Some won't." },
      { type: "paragraph", text: "Next time, it might be a different combination of people." },
      { type: "paragraph", text: "This works particularly well for casual things you're happy to do anyway: drinks, walks, coffee, watching a game, going to a market, dinner or anything else that doesn't depend on a particular group being there." },
      { type: "paragraph", text: "You're not trying to find the perfect date. You're giving people more opportunities to see each other." },
      { type: "heading", text: "Loopt is designed for this kind of low-pressure plan" },
      { type: "paragraph", text: "On Loopt, you can put up what you're doing and add the people you'd like to include." },
      { type: "paragraph", text: "They can come if they're free or leave the plan if they can't make it. There are no read receipts, so adding someone doesn't create the same pressure to immediately respond to a message." },
      { type: "paragraph", text: "That means you can share a plan without needing it to become a whole conversation about everyone's availability first." },
      { type: "paragraph", text: "And the plan doesn't need to start with a big group. Maybe you already have dinner planned with one friend and think a few other people would get on. You can add them too." },
      { type: "paragraph", text: "It can be as simple as:" },
      { type: "strong", text: "we're doing this, come if you fancy it." },
      { type: "heading", text: "You can still plan ahead when you need to" },
      { type: "paragraph", text: "Making the plan first doesn't mean never coordinating schedules." },
      { type: "paragraph", text: "Sometimes finding a shared date really is the problem. If you're trying to get five old friends who live in different places together for the first time in six months, comparing calendars is probably worth doing." },
      { type: "paragraph", text: "You can also use a mix of both approaches." },
      { type: "paragraph", text: "Plan the things where everyone really matters further ahead. For smaller everyday plans, be more spontaneous and let whoever's free come along." },
      { type: "paragraph", text: "That can create more chances to see each other without every catch-up requiring weeks of organising." },
      { type: "heading", text: "Don't let a full calendar stop you seeing your friends" },
      { type: "paragraph", text: "When everyone is busy, it can feel like seeing each other requires finding a rare gap when every calendar magically lines up." },
      { type: "paragraph", text: "It doesn't always have to." },
      { type: "paragraph", text: "Sometimes you can start with what one or two of you are already doing, open it up to other people you'd like to see, and let everyone decide whether this one works for them." },
      { type: "paragraph", text: "Not everyone will make every plan. They don't need to." },
      { type: "paragraph", text: "The point is to make it easier for the times that do work to actually happen." },
    ],
  },
  {
    slug: "organise-plans-big-group-of-friends",
    path: "/answers/organise-plans-big-group-of-friends",
    title: "How do you organise plans with a big group of friends?",
    description: "Organising plans with a big group is easier when the plan is concrete, important details stay clear and you don't wait for everyone to agree.",
    datePublished: "2026-08-31",
    content: [
      { type: "paragraph", text: "The easiest way to organise plans with a big group of friends is to make the plan concrete, keep the important details somewhere everyone can find them, and avoid waiting for every single person to agree before anything happens." },
      { type: "paragraph", text: "Big group plans often become difficult because the plan and the conversation about the plan end up mixed together. The date gets buried in messages, nobody is quite sure who's coming, new people join halfway through, and every change creates another round of chat." },
      { type: "paragraph", text: "Separating those two things can make a big difference." },
      { type: "heading", text: "Start with an actual plan" },
      { type: "paragraph", text: "“Does anyone want to do something next weekend?” sounds easygoing, but with a big group it can quickly turn into ten different suggestions and fifteen different schedules." },
      { type: "paragraph", text: "Give people something concrete to respond to instead." },
      { type: "paragraph", text: "For example:" },
      { type: "strong", text: "Bowling next Friday at 7pm" },
      { type: "paragraph", text: "It doesn't have to be final. People can suggest another time or place if it doesn't work. But starting with an actual plan makes it much easier to get to a decision." },
      { type: "paragraph", text: "And if you're organising a large group, don't assume you always need to find a date that works for absolutely everyone. Sometimes waiting for unanimous availability is the reason the plan never happens." },
      { type: "heading", text: "Keep the plan separate from the conversation" },
      { type: "paragraph", text: "Group chats are useful for talking. They're less useful as a permanent home for a plan." },
      { type: "paragraph", text: "Someone joins later and needs to know what's happening. The time changes but the original message still says 7pm. Someone asks who's actually coming. Important details gradually disappear underneath everything else people are talking about." },
      { type: "paragraph", text: "There's another problem too: in a big group, people can become reluctant to message because they know they're notifying everyone." },
      { type: "paragraph", text: "Muting the chat solves the noise problem, but can create another one. Now people risk missing something important." },
      { type: "paragraph", text: "A better approach is to keep the plan itself somewhere clear, then let the conversation happen around it." },
      { type: "heading", text: "On Loopt, you can mute the chat without muting the plan" },
      { type: "paragraph", text: "Loopt separates a plan from the messages around it." },
      { type: "paragraph", text: "The plan holds the important information, while its chat gives everyone somewhere to talk." },
      { type: "paragraph", text: "If the conversation gets busy, people can mute the messages without missing important updates to the plan itself. So they don't need a notification every time somebody sends a message, but can still be notified when important plan details change." },
      { type: "paragraph", text: "That gives people a bit more freedom to actually use the chat without feeling like every message has to be important enough to notify the whole group." },
      { type: "paragraph", text: "If you need everyone's opinion on something, you can ask in the chat too. People can reply or use a thumbs-up to quickly show agreement, then the plan itself can be updated once you've decided." },
      { type: "heading", text: "Let people bring people without letting the plan get out of control" },
      { type: "paragraph", text: "With a big social plan, you might not know everyone who could end up coming." },
      { type: "paragraph", text: "Sometimes that's part of the fun." },
      { type: "paragraph", text: "On Loopt, you can add people and let them add people they know too. That means one person doesn't necessarily have to organise everybody or know everyone from the beginning." },
      { type: "paragraph", text: "But opening a plan up doesn't mean it has to grow indefinitely." },
      { type: "paragraph", text: "Say you've booked a bowling lane for eight people. You can cap the plan at eight, so people can keep joining until you've filled the spaces." },
      { type: "paragraph", text: "Or maybe you started with an open plan and now have enough people. You can stop sharing it so the plan doesn't keep spreading." },
      { type: "paragraph", text: "That lets a plan grow naturally while still giving you control when you need it." },
      { type: "heading", text: "Bigger plans sometimes need a bit more control" },
      { type: "paragraph", text: "Not every group plan needs lots of settings." },
      { type: "paragraph", text: "Drinks at the pub might be as simple as putting up the plan and seeing who's around." },
      { type: "paragraph", text: "But as plans get bigger, there are times when you want more control over how they spread." },
      { type: "paragraph", text: "Loopt Premium gives you more granular control over who can add other people. So rather than applying the same rule to everyone, you can change an individual's add access when you need to." },
      { type: "paragraph", text: "The point isn't to turn a casual plan into a formal event. It's to give you a bit more control when the size or shape of the plan calls for it." },
      { type: "heading", text: "Don't make a big plan more complicated than it needs to be" },
      { type: "paragraph", text: "A bigger group doesn't necessarily need more organising. It needs less ambiguity." },
      { type: "paragraph", text: "Start with something concrete. Give the important details somewhere clear to live. Let people talk without making the conversation the source of truth. Let the plan grow through people if you want it to, and put limits around that growth when you need them." },
      { type: "paragraph", text: "The less time everyone spends working out what's happening, the easier it is to actually get everyone together." },
    ],
  },
  {
    slug: "best-app-for-making-plans-with-friends",
    path: "/answers/best-app-for-making-plans-with-friends",
    title: "What's the best app for making plans with friends?",
    description: "The best app for making plans with friends depends on what actually makes planning difficult for your group, from finding a time to organising everyday plans.",
    datePublished: "2026-08-31",
    content: [
      { type: "paragraph", text: "The best app for making plans with friends depends on what actually makes planning difficult for your group." },
      { type: "paragraph", text: "If finding a time is the problem, a shared calendar or scheduling poll might be best. If you're organising a bigger party or more formal event, an event platform may make more sense. And if your friends already make plans easily in a group chat, you might not need another app at all." },
      { type: "strong", text: "Loopt is designed for something slightly different: everyday social plans. Put up what you're doing, add some people, and, where it makes sense, let them add people they know too." },
      { type: "paragraph", text: "So rather than looking for the planning app with the longest feature list, start with the problem you're actually trying to solve." },
      { type: "heading", text: "If finding a date is the hard part" },
      { type: "paragraph", text: "Sometimes making the plan is easy. Finding a time when everyone is free isn't." },
      { type: "paragraph", text: "In that case, tools built around shared availability or scheduling polls are probably the most useful. Howbout is built around a shared social calendar, while Doodle lets a group vote on possible times." },
      { type: "paragraph", text: "You don't necessarily need a whole new way of making plans. You just need a better way to answer: when can everyone do it?" },
      { type: "heading", text: "If you're organising a bigger event" },
      { type: "paragraph", text: "A birthday party or bigger organised event can need something different again." },
      { type: "paragraph", text: "You might want a dedicated event page, more formal responses from people or other event-specific tools. Platforms such as Partiful are built much more around that kind of occasion." },
      { type: "paragraph", text: "That's different from deciding to go to the pub on Thursday and seeing who fancies coming." },
      { type: "heading", text: "If your group chat already works, keep using it" },
      { type: "paragraph", text: "Not every friendship group needs a planning app." },
      { type: "paragraph", text: "If someone suggests dinner in WhatsApp, everyone replies, you pick Thursday and nobody loses track of what's happening, you've solved the problem." },
      { type: "paragraph", text: "Things get more frustrating when the plan is buried between hundreds of other messages, nobody knows who's actually in, or one person has to keep chasing everyone and repeating the details." },
      { type: "paragraph", text: "That's when moving the plan somewhere of its own can become useful." },
      { type: "heading", text: "If you make casual plans that can grow through people" },
      { type: "paragraph", text: "This is the kind of planning Loopt is designed for." },
      { type: "paragraph", text: "You can put up an everyday plan, add the people you want to include and decide whether they can add other people too." },
      { type: "paragraph", text: "Say you're going for drinks after work." },
      { type: "paragraph", text: "You add three friends. One adds someone from their flat. Another adds a friend you met once before. Someone can't make it this time, but they can leave this plan and still be listed as one of your connections for the next time you're making plans." },
      { type: "paragraph", text: "The plan doesn't need to start with one perfectly defined group of people. It can grow through the people already involved." },
      { type: "paragraph", text: "That's one of the biggest differences between Loopt and tools that mainly help an existing group find a date." },
      { type: "heading", text: "So which planning app should you use?" },
      { type: "paragraph", text: "Choose based on the bit you actually find difficult." },
      { type: "paragraph", text: "If it's finding a time, look for scheduling or shared-calendar tools." },
      { type: "paragraph", text: "If it's organising a bigger or more formal occasion, an event platform may suit you better." },
      { type: "paragraph", text: "If it's choosing what to do, there are apps specifically designed around suggestions and group voting." },
      { type: "paragraph", text: "If your group chat works perfectly well, keep it." },
      { type: "paragraph", text: "And if you want somewhere for everyday plans to live, with the option for plans to grow naturally through people you know, that's what Loopt is built for." },
      { type: "paragraph", text: "The goal isn't to add another app to your life for the sake of it. It's to make it easier to actually spend time together." },
    ],
  },
  {
    slug: "how-to-make-friends-at-uni",
    path: "/answers/how-to-make-friends-at-uni",
    title: "How do you make friends at uni?",
    description: "Making friends at uni isn't only about meeting people. Turning new acquaintances into friends usually means making another plan and spending time together again.",
    datePublished: "2026-08-30",
    content: [
      { type: "paragraph", text: "The usual advice for making friends at uni is good: talk to people on your course, join societies, go to things during Freshers and be willing to make the first move." },
      { type: "paragraph", text: "But there's another part that's easy to overlook." },
      { type: "strong", text: "Meeting people gives you acquaintances. Becoming friends usually means finding ways to keep spending time together." },
      { type: "paragraph", text: "So when you meet someone you get on with, don't just swap Instagrams and hope you bump into each other again. Make a plan. Bring a few people together. Do something else the following week. Let people bring people they know." },
      { type: "paragraph", text: "That's how a collection of new faces can gradually start feeling like your people." },
      { type: "heading", text: "Don’t just meet people. Make a second plan." },
      { type: "paragraph", text: "At the beginning of uni, you can meet a ridiculous number of people without becoming particularly close to any of them." },
      { type: "paragraph", text: "The useful next step is to turn “we should do something sometime” into an actual plan." },
      { type: "paragraph", text: "It doesn't need to be a big night out. Get coffee after a lecture. Grab food. Study together. Go to a pub quiz. Cook dinner. Go to a society event together." },
      { type: "paragraph", text: "The activity matters less than giving yourselves another reason to spend time together." },
      { type: "heading", text: "You can bring separate friendships together" },
      { type: "paragraph", text: "You don't necessarily need to find an existing friendship group and somehow get into it." },
      { type: "paragraph", text: "You might meet Amy in halls, James on your course and Sophie at a society. If you like all three of them, invite them to something together." },
      { type: "paragraph", text: "Then maybe one of them brings someone they know." },
      { type: "paragraph", text: "That is often how a social circle starts taking shape: different connections gradually overlap." },
      { type: "strong", text: "You don't only find friendship groups. You can gradually make one." },
      { type: "heading", text: "Loopt can make that bit easier" },
      { type: "paragraph", text: "Loopt is built for everyday plans like this." },
      { type: "paragraph", text: "You can put up what you're doing, add the people you want to include, and decide whether they can add other people too." },
      { type: "paragraph", text: "For example:" },
      { type: "example", lines: ["pub after lectures", "Thursday · 7pm"] },
      { type: "paragraph", text: "Add a few people you think might get on. If they can add others too, the plan can grow naturally through people rather than one person having to know everybody from the start." },
      { type: "paragraph", text: "You're still meeting people through people. Loopt just gives the plan somewhere to happen." },
      { type: "heading", text: "The really important bit is doing it again" },
      { type: "paragraph", text: "One good night together doesn't automatically create a friendship group." },
      { type: "paragraph", text: "What matters is making it easy for the people who got on to see each other again." },
      { type: "paragraph", text: "Loopt is designed around this too. The same people can be there for future plans, so someone in the group can start the next thing rather than the original organiser always having to recreate everything." },
      { type: "paragraph", text: "You put up Thursday drinks." },
      { type: "paragraph", text: "Someone else puts up a Sunday walk." },
      { type: "paragraph", text: "Another person adds everyone to a pub quiz the following week." },
      { type: "paragraph", text: "Someone misses one of them but comes to the next." },
      { type: "paragraph", text: "The aim isn't to organise your friendship. It's simply to make it easier for seeing each other once to turn into seeing each other again." },
      { type: "heading", text: "Meeting friends of friends can widen your circle too" },
      { type: "paragraph", text: "As plans start overlapping, you may also meet people through people you already know." },
      { type: "paragraph", text: "Loopt's connections are designed around this kind of real-world overlap. Its “you might know” suggestions can surface second-level connections you've shared a plan with, rather than matching you with random strangers." },
      { type: "paragraph", text: "So the circle can grow through actual people and plans you've been part of." },
      { type: "heading", text: "What if I haven't found my people during Freshers?" },
      { type: "paragraph", text: "Don't treat Freshers as a deadline for finding your friendship group." },
      { type: "paragraph", text: "You don't need twenty new best friends in the first week. A handful of people you'd genuinely like to see again is enough to start with." },
      { type: "paragraph", text: "Pick someone. Suggest something. Bring a few people together if it feels natural." },
      { type: "paragraph", text: "Then do it again." },
    ],
  },
];

export function getAnswerBySlug(slug: string | undefined) {
  return answers.find((answer) => answer.slug === slug);
}
